name: Build Dockerfiles

on:
  push:
    paths:
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    name: Build Dockerfile PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Dockerfile
        run: docker build docker/${{ matrix.php }}
